name: Sync to Hugging Face
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to HuggingFace Space
        uses: huggingface/huggingface-space-sync@main
        with:
          hf-token: ${{ secrets.HF_token }}
          hf-username: ${{ secrets.HF_username }}
          space-name: watermark-remover
